### ISSUE TITLE
some issue wrt scheme.about.code 

### ISSUE THREAD

**Issue by katy45** [vipranarayan14/vtranslit#5]
return _scheme.about.code === schemeCode;
                           ^

TypeError: Cannot read property 'code' of undefined
    at /home/karthik/Apps/myApp/node_modules/vtranslit/dist/vtranslit.npm.js:1003:28
    at Array.find (<anonymous>)
    . ......

**Comment by vipranarayan14** [comment]
Please provide the steps to reproduce the error and other relevant information like vtranslit version, Node.js version and Operating System. 

And did you clone the repository or install it from npm?

**Comment by vipranarayan14** [comment]
@katy45 You might have got the error by following the [Node Usage](https://github.com/vipranarayan14/vtranslit#node-usage) instructions from the README.md.

The Node Usage instructions were old. I have updated it.

I think now you can follow those instructions and get it running properly.
